spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: root
    password: root-order-db
  jpa:
    hibernate:
      ddl-auto: update
      #create-drop
    show-sql: true
    generate-ddl: true
